alias dot="/usr/bin/git --git-dir=$HOME/.dot/ --work-tree=$HOME"
alias ls="ls --color=auto -F"
alias l="ls --color=auto -F"
alias ll="ls -Al"
alias la="ls -A"
alias lla="ls -lA"
alias lal="ls -Al"
alias c="clear"
alias dk="docker kill"
alias dps="docker ps"
alias dka="echo Killing containers:&& docker ps -q | xargs docker kill"
alias dca="docker image prune -f && docker container prune -f && docker system prune -f"
alias dwa="watch docker ps"
alias gst="git status"
alias ga="git add ."
alias gac="git add . && git commit"
alias gc="git commit"
alias gd="git diff"
alias gcm="git checkout master"
alias gco="git checkout"
alias gcoo="git checkout -- ."
alias gpl="git pull"
alias gps="git push"
alias gp="git pull"
alias gf="git fetch"